name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: Format code
        run: npm run format
      - name: Lint code
        run: npm run lint
      - name: Lint styles
        run: npm run stylelint
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
